import {useState,useEffect,type CSSProperties} from 'react';
import {Chessboard} from 'react-chessboard';
import type {Square} from 'chess.js';
import {Chess} from '@/lib/chess';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
import {Button} from './ui/button';
const names:Record<string,string>={p:'pawn',r:'rook',n:'knight',b:'bishop',q:'queen',k:'king'};
export function Board({fen,orientation='w',onMove,disabled=false,lastMove,line}:{fen:string;orientation?:'w'|'b';onMove:(m:string)=>void;disabled?:boolean;lastMove?:string;line?:string[]}){const [selected,setSelected]=useState<string|null>(null);const [promotion,setPromotion]=useState<{from:string;to:string}|null>(null);useEffect(()=>{setSelected(null);setPromotion(null)},[fen]);const b=new Chess(fen);const styles:Record<string,CSSProperties>={};if(lastMove)for(const s of [lastMove.slice(0,2),lastMove.slice(2,4)])styles[s]={backgroundColor:'#e4cf6570'};if(selected){styles[selected]={backgroundColor:'#cfdf7299'};for(const m of b.moves({square:selected as Square,verbose:true}))styles[m.to]={backgroundImage:'radial-gradient(circle, #102a2b55 20%, transparent 23%)'};}
 function attempt(from:string,to:string){if(disabled)return false;const candidates=b.moves({square:from as Square,verbose:true}).filter(m=>m.to===to);if(!candidates.length)return false;if(candidates.some(m=>m.promotion)){setPromotion({from,to});return false;}onMove(from+to);setSelected(null);return true;}
 function click(square:string){if(disabled)return;if(selected&&attempt(selected,square))return;const p=b.get(square as Square);setSelected(p?.color===b.turn()?square:null);}
 return <><div className="chessboard"><Chessboard options={{id:'greenroom-board',position:fen,boardOrientation:orientation==='w'?'white':'black',allowDragging:!disabled,canDragPiece:({piece})=>!disabled&&piece.pieceType[0]===b.turn(),onPieceDrop:({sourceSquare,targetSquare})=>targetSquare?attempt(sourceSquare,targetSquare):false,onSquareClick:({square})=>click(square),squareStyles:styles,darkSquareStyle:{backgroundColor:'#6a8667'},lightSquareStyle:{backgroundColor:'#e5e6ce'},boardStyle:{borderRadius:'4px',overflow:'hidden'},animationDurationInMs:160,arrows:line?.length?[{startSquare:line[0].slice(0,2),endSquare:line[0].slice(2,4),color:'#f4c768cc'}]:[],squareRenderer:({square,children})=>{const p=b.get(square as Square);return <div role="button" tabIndex={disabled?-1:0} aria-label={`${square}, ${p?(p.color==='w'?'white ':'black ')+names[p.type]:'empty'}`} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();click(square)}}} style={{width:'100%',height:'100%'}}>{children}</div>}}/></div><Dialog open={Boolean(promotion)} onOpenChange={v=>{if(!v)setPromotion(null)}}><DialogContent><DialogTitle>Choose your promotion</DialogTitle><DialogDescription>Your pawn has reached the last rank.</DialogDescription><div className="row">{['q','r','b','n'].map(p=><Button key={p} onClick={()=>{if(promotion)onMove(promotion.from+promotion.to+p);setPromotion(null)}}>{names[p]}</Button>)}</div></DialogContent></Dialog></>;
}
